version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:  
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: house_parser
      POSTGRES_USER: postgres
    ports:    
      - 5433:5432
    volumes:
      - db:/var/lib/postgres/data
      - ./postgres:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db:
    driver: local